---
# tasks file for docker

- name: Install Docker packages
  apt: pkg=docker.io state=latest
  tags: docker

- name: Create symlink
  file: src=/usr/bin/docker.io dest=/usr/local/bin/docker state=link force=yes
  tags: docker

- name: Add autocomplete
  command: sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
  tags: docker