---

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes

- name: restart ntp
  service: name=ntp state=restarted
  sudo: yes

- name: restart jenkins
  command: java -jar /usr/share/jenkins-cli/jenkins-cli.jar -s http://localhost:8080 safe-restart
  sudo: yes